### ISSUE TITLE
Ecto Error with Batched Queries

### ISSUE THREAD

**Issue by zerosym** [absinthe-graphql/dataloader#12]
I'm getting an error from Ecto when using dataloader with a batched GraphQL query request.  Specifically I have two Ecto schemas, Foo and Bar, which both reference a third, Baz, via association.
The batched query operates against both Foo and Bar, utilizing the same dataloader(Baz).

This line in the ecto source triggers the error I'm receiving:
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/preloader.ex#L133

Not sure how to fix this, or if this is something that can be handled in the dataloader code.

The traceback: 

> ** (ArgumentError) expected a homogeneous list containing the same struct, got: Foo and Bar
>     (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
>     (dataloader) lib/dataloader/ecto.ex:297: Dataloader.Source.Dataloader.Ecto.run_batch/2
>     (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
>     (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
>     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

https://github.com/absinthe-graphql/dataloader/blob/master/lib/dataloader/ecto.ex#L297

**Comment by zerosym** [comment]
I ended up just duplicating the source in the loader to have separate ones for Foo and Bar to reference.  Leads to two separate db queries against the Baz table, but good enough for my current use case.

```elixir
Dataloader.new()
|> Dataloader.add_source(BazOne, Baz.data())
|> Dataloader.add_source(BazTwo, Baz.data())
