### ISSUE TITLE
get grouping_error in dataloader

### ISSUE THREAD

**Issue by mydearxym** [absinthe-graphql/dataloader#30]
Hi guys

give a schema like this:

```elixir 
schema "communities" do
    field(:title, :string)
    field(:desc, :string)
    ....

    many_to_many(
      :posts,
      Post,
      join_through: "communities_posts",
      join_keys: [community_id: :id, post_id: :id]
    )
    timestamps(type: :utc_datetime)
end
```
Absinthe Schema :
```elixir
object :community do
    field(:id, :id)
    field(:title, :string)
    field(:desc, :string)
    ... 
    field :posts_count, :integer do
      arg(:count, :count_type, default_value: :count)
      arg(:type, :community_type, default_value: :community)

      resolve(dataloader(CMS, :posts))
      middleware(M.ConvertToInt)
    end
end
```
dataloader query: 

```elixir
def query(Post, args) do
    Post
    |> select([p], count(p.id))
end
```

what i want is very simple: get the total postCount of the community, but a got GROUP BY errors : 

```elixir
[debug] ABSINTHE schema=MastaniServerWeb.Schema variables=%{}
---
{
  community(id: 3) {
    title
    postsCount
  }
}
---
[debug] QUERY OK source="communities" db=5.4ms
SELECT c0."id", c0."title", c0."desc", c0."user_id", c0."inserted_at", c0."updated_at" FROM "communities" AS c0 WHERE (c0."id" = $1) [3]
[debug] QUERY ERROR source="cms_posts" db=20.1ms
SELECT c1."id", count(c0."id") FROM "cms_posts" AS c0 INNER JOIN "communities" AS c1 ON c1."id" = ANY($1) INNER JOIN "communities_posts" AS c2 ON c2."community_id" = c1."id" WHERE (c2."post_id" = c0."id") ORDER BY c1."id" [[3]]
[info] Sent 200 in 909ms
[error] Task #PID<0.487.0> started from #PID<0.485.0> terminating
** (Postgrex.Error) ERROR 42803 (grouping_error): column "c1.id" must appear in the GROUP BY clause or be used in an aggregate function
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (dataloader) lib/dataloader/ecto.ex:398: Dataloader.Source.Dataloader.Ecto.run_batch/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<5.80139747/1 in Dataloader.Source.Dataloader.Ecto.run/1>, [{{:assoc, MastaniServer.CMS.Community, #PID<0.475.0>, :posts, MastaniServer.CMS.Post, %{count: :count, type: :community}}, #MapSet<[{[3], %MastaniServer.CMS.Community{__meta__: #Ecto.Schema.Metadata<:loaded, "communities">, author: #Ecto.Association.NotLoaded<association :author is not loaded>, desc: "js community", editors: #Ecto.Association.NotLoaded<association :editors is not loaded>, id: 3, inserted_at: #DateTime<2018-02-06 11:25:46.662701Z>, posts: #Ecto.Association.NotLoaded<association :posts is not loaded>, subscribers: #Ecto.Association.NotLoaded<association :subscribers is not loaded>, title: "js", updated_at: #DateTime<2018-02-06 11:25:46.662785Z>, user_id: 1}}]>}]]
```

**Comment by mydearxym** [comment]
thanks for the magic !

**Comment by mydearxym** [comment]
hi @benwilson512 

just one more question, how can i access the args in run_batch/5 funciton?

```elixir
resolve fn community, args, %{context: %{loader: loader}} ->
  loader
  |> Dataloader.load(CMS, {:one, Post}, posts_count: community.id)
  |> on_load(fn loader ->
    {:ok, Dataloader.get(loader, CMS, {:one, Post}, posts_count: community.id)
  end)
end
```

```elixir
def run_batch(Post, post_query, :posts_count, community_ids, repo_opts) do
   # how can i access the args?  
  query = from p in post_query,
    ..... 
end

```

**Comment by benwilson512** [comment]
@mydearxym args are supposed to be handled / applied to the `post_query` via the `query` function.

**Comment by mydearxym** [comment]
for example the args passed  by user is 
```elixir
%{filter: %{first: 2, sort: :desc_inserted}}
```

it will handled / applied to the post_query automatic ?

**Comment by benwilson512** [comment]
No, there is no automatic argument handling, the default `query` function is a pass through.

**Comment by mydearxym** [comment]
could you please give me a example ?
