### ISSUE TITLE
Trouble getting Dataloader to work in a fresh umbrella application

### ISSUE THREAD

**Issue by sergiotapia** [absinthe-graphql/dataloader#88]
Even recompiling absinthe doesn’t fix it.

```
      {:phoenix, "~> 1.4.15"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:gettext, "~> 0.11"},
      {:nuki, in_umbrella: true},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:dataloader, "~> 1.0"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"}
```

I’m in an umbrella application, added absinthe and dataloader to the phoenix app within the umbrella, and added only dataloader to the logic app within the umbrella.

Tried deleting `_build` and `deps` but the same result.

```
defmodule NukiWeb.Schema.ContentTypes do
  import Absinthe.Resolution.Helpers, only: [dataloader: 1]
  use Absinthe.Schema.Notation

# ====

$ iex -S mix phx.server
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

==> nuki_web
Compiling 12 files (.ex)

== Compilation error in file lib/nuki_web/schema/content_types.ex ==
** (CompileError) lib/nuki_web/schema/content_types.ex:12: undefined function dataloader/1
    (elixir 1.10.2) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.6) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

I'm wondering if this is caused by my core app only having dataloader in mix.exs for:

```
defmodule Nuki.DataloaderRepo do
  def data() do
    Dataloader.Ecto.new(Nuki.Repo, query: &query/2)
  end

  def query(queryable, _params) do
    queryable
  end
end
```

And my phoenix app having dataloader **and** absinthe libs.

Appreciate any insight from anyone who used this library in an umbrella setting.

**Comment by sergiotapia** [comment]
Hm... still stuck on this any ideas @benwilson512

**Comment by benwilson512** [comment]
Hi @sergiotapia, dataloader is an explicit dependency of nuki? What Elixir version are you on?

**Comment by stap-pipeline** [comment]
@benwilson512 Yep

Nuki's mix.exs:

```
 defp deps do
    [
      {:ecto_sql, "~> 3.1"},
      {:postgrex, ">= 0.0.0"},
      {:jason, "~> 1.0"},
      {:comeonin, "~> 5.1"},
      {:argon2_elixir, "~> 2.1"},
      {:timex, "~> 3.6"},
      {:ex_aws, "~> 2.1"},
      {:ex_aws_s3, "~> 2.0"},
      {:nanoid, "~> 2.0"},
      {:ex_machina, "~> 2.4"},
      {:dataloader, "~> 1.0"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"}
    ]
  end
```

And nuki_web's mix.exs:

```
defp deps do
    [
      {:phoenix, "~> 1.4.15"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:gettext, "~> 0.11"},
      {:nuki, in_umbrella: true},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:dataloader, "~> 1.0"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"}
    ]
  end
```

**Comment by sergiotapia** [comment]
@benwilson512 Yep

Nuki's mix.exs:

```
 defp deps do
    [
      {:ecto_sql, "~> 3.1"},
      {:postgrex, ">= 0.0.0"},
      {:jason, "~> 1.0"},
      {:comeonin, "~> 5.1"},
      {:argon2_elixir, "~> 2.1"},
      {:timex, "~> 3.6"},
      {:ex_aws, "~> 2.1"},
      {:ex_aws_s3, "~> 2.0"},
      {:nanoid, "~> 2.0"},
      {:ex_machina, "~> 2.4"},
      {:dataloader, "~> 1.0"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"}
    ]
  end
```

And nuki_web's mix.exs:

```
defp deps do
    [
      {:phoenix, "~> 1.4.15"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:gettext, "~> 0.11"},
      {:nuki, in_umbrella: true},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:dataloader, "~> 1.0"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"}
    ]
  end
```

The umbrella's mix.exs has no deps set.

```
sergiotapia at Sergios-MBP-2 in ~/Work/nuki/nuki_umbrella on develop [!?]
$ mix compile
==> nuki_web
Compiling 12 files (.ex)

== Compilation error in file lib/nuki_web/schema/content_types.ex ==
** (CompileError) lib/nuki_web/schema/content_types.ex:12: undefined function dataloader/1
    (elixir 1.10.2) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.6) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

defmodule NukiWeb.Schema.ContentTypes do
  import Absinthe.Resolution.Helpers, only: [dataloader: 1]
  use Absinthe.Schema.Notation

  object :listing do
    field(:id, :id)
    field(:title, :string)
    field(:slug, :string)
    field(:description, :string)
    field(:price, :integer)

    field(:user, :user, resolve: dataloader(Nuki.Repo))
  end
end
```

**Comment by sergiotapia** [comment]
I figured it out @benwilson512 , this fixed it:

```
defmodule NukiWeb.Schema.ContentTypes do
  use Absinthe.Schema.Notation
  import Absinthe.Resolution.Helpers, only: [dataloader: 1]
```

I would like to share this set up guide "Adding absinthe/dataloader to your umbrella elixir application." - do you think I can do this in the repo, as a Wiki page or similar?

**Comment by benwilson512** [comment]
Hi @sergiotapia I'm glad we could get it sorted out. Technically though, the solution and the problem have nothing to do with umbrella applications right? Or are you saying you have other content that is relevant for umbrella apps you'd like to share? If so, please feel free to open a PR with a guide markdown document within Absinthe.

**Comment by sergiotapia** [comment]
That is correct - the issue had nothing to do with the umbrella app. I hope this thread helps people. I'll work on a little Wiki guide as well!
